#!/usr/bin/env bash
# write a Bash script that displays information about subdomains
# Requirements:
# script accepts 1 or 2 arguments:
# mandatory: 1 - domain name to audit
# optional: 2 - subdomain
# Must use:
# awk
# at least one Bash function


information ()
{
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
    then
	information "$1" "$subdomain"
    fi
done
