#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to respect above requirements
# Requirements

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx stop
redirect="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"
sudo sed -i "s/server_name _;/$redirect/" /etc/nginx/sites-enabled/default
sudo service nginx restart
