#!/usr/bin/env bash
# a bash script that configures a brand new Ubuntu machine to the requirements
# Requirements:
# configures the Nginx server to have a custom 404 page 
# the page must return an HTTP 404 error code
# the page must contain the string "Ceci n'est pas une page"
 
sudo apt update
sudo apt install -y nginx
sudo mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" | sudo tee -a /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/404.html
sudo service nginx stop
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx start

