#!/usr/bin/env bash
# write a Bash script that installs and configures HAproxy on your server.
# Requirements:
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get update && sudo apt-get install -y haproxy=2.5.\*

echo "ENABLED=1" >> /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.orig}
sudo touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 53450-web-01 54.237.5.137 check
    server 53450-web-02 34.237.91.118 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
