#!/usr/bin/env bash
# write a Bash script that installs and configures HAproxy on your server.
# Requirements:
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

sudo apt update && sudo apt install -y haproxy

printf %s "frontend main
	bind *:80
	mode http
	default_backend servers

backend servers
	balance roundrobin
  server 53450-web-01 54.237.5.137 check
  server 53450-web-02 34.237.91.118 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
