#!/usr/bin/env bash
# Write a Bash script that configures a server so that Nginx is running, and
#+ listening on port 80 of all the server’s active IPv4 IPs

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
