#!/usr/bin/env bash
# a Bash script that configures a server so that Nginx is listening on port 80
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
kill "$(pgrep 'nginx' | head -1)"
