#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd using a while loop
# Your script should only display:
# username
# user id
# Home directory path for the use

while read -r line;
do
   echo "$line" | cut -d ':' -f1,3,6
done < /etc/passwd
