#!/usr/bin/env bash
# a Bash script that installs and configures a ufw firewall
#+ to block all incoming traffic, except the following TCP ports:
#+ 22 (SSH)
#+ 80 (HTTP)
#+ 443 (HTTPS SSL)

yes | sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw status
yes | sudo ufw enable
sudo ufw status
