#!/usr/bin/env bash
# a Bash script that configures the container
# Requirements:
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080

pkill -f apache2
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.BAK
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
chmod 0644 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
service nginx reload
sudo -u nginx service nginx start
