#!/usr/bin/env bash
# a Bash script that configures the container
# Requirements:
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080

pkill -f apache2
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
service nginx reload
sudo -u nginx service nginx start

